FROM node:25.6.1-alpine
LABEL authors="unstoppable"

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN chown -R node:node /app
USER node

EXPOSE 5173



CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]