[project]
name = "dndsettlements"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "sqlmodel>=0.0.46",
]

[project.scripts]
dndsettlements = "dndsettlements:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
